### ISSUE TITLE
pip install doesn't provide migration.. 

### ISSUE THREAD

**Issue by dz0** [mikeengland/django-setty#2]
`$ pip install django-setty`
`Successfully installed django-picklefield-2.0 django-setty-2.0.0 python-memcached-1.59`

`$ python manage.py migrate setty`
`CommandError: App 'setty' does not have migrations.` -- why -- I see it on github?

I had to create it myself, which might be problem on production

`$ python manage.py makemigrations setty`
```
Migrations for 'setty':
  /home/vagrant/tableair-cloud/ta_env/lib/python3.5/site-packages/setty/migrations/0001_initial.py
    - Create model SettySettings
```

Py 3.5
Django  1.11.7

**Comment by mikeengland** [comment]
Thanks for reporting. I will take a look at this later.

**Comment by mikeengland** [comment]
Built as 2.0.1. Please try again!
