### ISSUE TITLE
When editting existing setting in Admin, value field is loaded empty 

### ISSUE THREAD

**Issue by dz0** [mikeengland/django-setty#3]
I use DB backend
1) I create setting: 
name="test"
type="integer"
value=42

2) it displays in admin list ok: "test=42"

3) I open edit/change: and I see "value" field empty -- not a tragedy (as representation shows "test=42") but still weirdness... 

screenshot: http://pix.toile-libre.org/upload/original/1553088164.png

Py 3.5
Django 1.11.7

**Comment by mikeengland** [comment]
Looks like it was due to the admin not being able to load model properties into fields by default. Fixed in v2.0.3!
